name: Add Timestamp to Markdown Files
 
on:
  gollum:

jobs:
  add-timestamp:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Add timestamp to markdown files
        run: |
          for file in $(find . -name '*.md'); do
            if grep -q '^Last updated:' "$file"; then
              sed -i "s/^Last updated:.*/Last updated: $(date -u '+%Y-%m-%d %H:%M:%S UTC')/" "$file"
            else
              echo -e "Last updated: $(date -u '+%Y-%m-%d %H:%M:%S UTC')\n$(cat $file)" > "$file"
            fi
          done

      - name: Commit and push changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add *.md
          git commit -m "Add/update timestamp to markdown files" || echo "No changes to commit"
          git push
